# Generated by Django 2.1.7 on 2019-03-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAnalysis_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CarAnalysis_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarComment',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_Comment_id', models.IntegerField(null=True)),
                ('NikeName', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CarNews',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=100)),
                ('UrlState', models.BooleanField()),
                ('Hcontent', models.TextField()),
                ('Mcontent', models.TextField()),
                ('Tcontent', models.TextField()),
                ('Acontent', models.TextField()),
                ('Date', models.DateField()),
                ('fromWhere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentAnalysis_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentAnalysis_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentComment',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_Comment_id', models.IntegerField(null=True)),
                ('NikeName', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentNews',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=100)),
                ('UrlState', models.BooleanField()),
                ('Hcontent', models.TextField()),
                ('Mcontent', models.TextField()),
                ('Tcontent', models.TextField()),
                ('Acontent', models.TextField()),
                ('Date', models.DateField()),
                ('fromWhere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceAnalysis_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceAnalysis_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceComment',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_Comment_id', models.IntegerField(null=True)),
                ('NikeName', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceNews',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=100)),
                ('UrlState', models.BooleanField()),
                ('Hcontent', models.TextField()),
                ('Mcontent', models.TextField()),
                ('Tcontent', models.TextField()),
                ('Acontent', models.TextField()),
                ('Date', models.DateField()),
                ('fromWhere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAnalysis_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAnalysis_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomeComment',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_Comment_id', models.IntegerField(null=True)),
                ('NikeName', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeNews',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=100)),
                ('UrlState', models.BooleanField()),
                ('Hcontent', models.TextField()),
                ('Mcontent', models.TextField()),
                ('Tcontent', models.TextField()),
                ('Acontent', models.TextField()),
                ('Date', models.DateField()),
                ('fromWhere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HouseAnalysis_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HouseAnalysis_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HouseComment',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_Comment_id', models.IntegerField(null=True)),
                ('NikeName', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseNews',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=100)),
                ('UrlState', models.BooleanField()),
                ('Hcontent', models.TextField()),
                ('Mcontent', models.TextField()),
                ('Tcontent', models.TextField()),
                ('Acontent', models.TextField()),
                ('Date', models.DateField()),
                ('fromWhere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportsAnalysis_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SportsAnalysis_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SportsComment',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_Comment_id', models.IntegerField(null=True)),
                ('NikeName', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=100)),
                ('UrlState', models.BooleanField()),
                ('Hcontent', models.TextField()),
                ('Mcontent', models.TextField()),
                ('Tcontent', models.TextField()),
                ('Acontent', models.TextField()),
                ('Date', models.DateField()),
                ('fromWhere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Kind', models.CharField(default='', max_length=100)),
                ('Pos_news_num', models.IntegerField()),
                ('Neu_news_num', models.IntegerField()),
                ('Neg_news_num', models.IntegerField()),
                ('Pos_comment_num', models.IntegerField()),
                ('Neu_comment_num', models.IntegerField()),
                ('Neg_comment_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyAnalysis_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyAnalysis_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_Score', models.FloatField()),
                ('Neg_score', models.FloatField()),
                ('Sentiment', models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyComment',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_Comment_id', models.IntegerField(null=True)),
                ('NikeName', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyNews',
            fields=[
                ('News_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=100)),
                ('UrlState', models.BooleanField()),
                ('Hcontent', models.TextField()),
                ('Mcontent', models.TextField()),
                ('Tcontent', models.TextField()),
                ('Acontent', models.TextField()),
                ('Date', models.DateField()),
                ('fromWhere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=200)),
                ('EmailField', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='technologynews',
            unique_together={('url', 'Title')},
        ),
        migrations.AddField(
            model_name='technologycomment',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.TechnologyNews'),
        ),
        migrations.AddField(
            model_name='technologyanalysis_news',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.TechnologyNews'),
        ),
        migrations.AddField(
            model_name='technologyanalysis_comment',
            name='Comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.TechnologyComment'),
        ),
        migrations.AlterUniqueTogether(
            name='sportsnews',
            unique_together={('url', 'Title')},
        ),
        migrations.AddField(
            model_name='sportscomment',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.SportsNews'),
        ),
        migrations.AddField(
            model_name='sportsanalysis_news',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.SportsNews'),
        ),
        migrations.AddField(
            model_name='sportsanalysis_comment',
            name='Comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.SportsComment'),
        ),
        migrations.AlterUniqueTogether(
            name='housenews',
            unique_together={('url', 'Title')},
        ),
        migrations.AddField(
            model_name='housecomment',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.HouseNews'),
        ),
        migrations.AddField(
            model_name='houseanalysis_news',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.HouseNews'),
        ),
        migrations.AddField(
            model_name='houseanalysis_comment',
            name='Comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.HouseComment'),
        ),
        migrations.AlterUniqueTogether(
            name='homenews',
            unique_together={('url', 'Title')},
        ),
        migrations.AddField(
            model_name='homecomment',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.HomeNews'),
        ),
        migrations.AddField(
            model_name='homeanalysis_news',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.HomeNews'),
        ),
        migrations.AddField(
            model_name='homeanalysis_comment',
            name='Comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.HomeComment'),
        ),
        migrations.AlterUniqueTogether(
            name='financenews',
            unique_together={('url', 'Title')},
        ),
        migrations.AddField(
            model_name='financecomment',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.FinanceNews'),
        ),
        migrations.AddField(
            model_name='financeanalysis_news',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.FinanceNews'),
        ),
        migrations.AddField(
            model_name='financeanalysis_comment',
            name='Comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.FinanceComment'),
        ),
        migrations.AlterUniqueTogether(
            name='entertainmentnews',
            unique_together={('url', 'Title')},
        ),
        migrations.AddField(
            model_name='entertainmentcomment',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.EntertainmentNews'),
        ),
        migrations.AddField(
            model_name='entertainmentanalysis_news',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.EntertainmentNews'),
        ),
        migrations.AddField(
            model_name='entertainmentanalysis_comment',
            name='Comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.EntertainmentComment'),
        ),
        migrations.AlterUniqueTogether(
            name='carnews',
            unique_together={('url', 'Title')},
        ),
        migrations.AddField(
            model_name='carcomment',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.CarNews'),
        ),
        migrations.AddField(
            model_name='caranalysis_news',
            name='News_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.CarNews'),
        ),
        migrations.AddField(
            model_name='caranalysis_comment',
            name='Comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsSentimentAnalysis.CarComment'),
        ),
    ]
