# Generated by Django 2.1.7 on 2019-03-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSentimentAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeanalysis_comment',
            name='Sentiment',
            field=models.CharField(choices=[('POS', '积极'), ('NEG', '消极'), ('NEU', '中性')], default='NEU', max_length=50),
        ),
    ]
